ALTER TABLE segments ADD COLUMN door INTEGER NOT NULL DEFAULT 0;
ALTER TABLE segments ADD COLUMN door_swing_in INTEGER NOT NULL DEFAULT 1;
ALTER TABLE segments ADD COLUMN door_hinge_side TEXT NOT NULL DEFAULT 'left';
